### ISSUE TITLE
How to properly configure compet maps

### ISSUE THREAD

**Issue by funny0619** [PaLeroy/competSMAC#1]
May I ask I can adapt the triggers in the SC2 editor? I used the SC2 editor to look into existing SMAC maps, but I'm unsure which triggers to change. Is there a way I can download compet maps? Thank you.

I keep getting the following error
`There is no room for another user in this game. This may not be a multiplayer map: /tmp/sc-q94w9ugb/StarCraft II/TempLaunchMap.SC2Map`

**Comment by funny0619** [comment]
I went into player properties and mirrored the AI team settings with the RL one. Seems to work now.

**Comment by PaLeroy** [comment]
Maps are in the folder https://github.com/PaLeroy/competSMAC/tree/main/smac/env/starcraft2/maps/SMAC_Maps

You have examples with 3m_compet and 3s52_compet.

From what I recall, you indeed need to change the unit type and put RL unit instead of AI unit in the SC2 editor.
